<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Hyva\Theme\ViewModel\StoreConfig $storeConfig */
$storeConfig = $viewModels->require(Hyva\Theme\ViewModel\StoreConfig::class);
$showMiniCart = $storeConfig->getStoreConfig(\Magento\Checkout\Block\Cart\Sidebar::XML_PATH_CHECKOUT_SIDEBAR_DISPLAY);
?>
<?php

$wrapperHeaderAdditionalCss = $block->getData('wrapper_header_additional_css') ?? [];
$headerContainerAdditionalCss = $block->getData('header_container_additional_css') ?? [];

?>
<script>
    function initHeader () {
        return {
            searchOpen: false,
            cart: {},
            getData(data) {
                if (data.cart) { this.cart = data.cart }
            }
        }
    }

</script>
<div id="header"
     class="relative z-30 w-full border-b shadow bg-container-lighter border-container-lighter <?= $escaper->escapeHtmlAttr(implode(" ", $wrapperHeaderAdditionalCss)) ?>"
     x-data="initHeader()"
     @keydown.window.escape="searchOpen = false;"
     @private-content-loaded.window="getData(event.detail.data)"
>
    <div class="relative container flex flex-wrap items-center justify-between w-full px-6 py-3 mx-auto mt-0 <?= $escaper->escapeHtmlAttr(implode(" ", $headerContainerAdditionalCss)) ?>">
        <!--Logo-->
        <?= $block->getChildHtml('logo'); ?>

        <!--Main Navigation-->
        <?= $block->getChildHtml('topmenu') ?>

        <div class="flex items-center order-3">
            <!--Compare Icon-->
            <?= $block->getChildHtml("header-content.compare-link") ?>

            <!--Search Icon-->
            <button id="menu-search-icon"
                    class="inline-block ml-1 no-underline sm:ml-3 hover:text-black"
                    @click.prevent="
                        searchOpen = !searchOpen;
                        $nextTick(function () { document.querySelector('#search').select(); });
                    "
            >
                <span class="sr-only label">
                    <?= $escaper->escapeHtml(__('Search')) ?>
                </span>

                <?= $heroicons->searchHtml(
                    "w-8 h-8 md:h-6 md:w-6 hover:text-black",
                    25,
                    25
                ) ?>
            </button>

            <!--Customer Icon & Dropdown-->
            <?= $block->getChildHtml('customer') ?>

            <?= $block->getChildHtml('cart.icon.before') ?>
            <!--Cart Icon-->
            <a id="menu-cart-icon"
               <?php if ($showMiniCart): ?>@click.prevent.stop="$dispatch('toggle-cart',{});"<?php endif ?>
               class="relative inline-block ml-1 no-underline sm:ml-3 hover:text-black"
               href="<?= $escaper->escapeUrl($block->getUrl('checkout/cart/index')) ?>"
            >
                <span class="sr-only label">
                    <?= $escaper->escapeHtml(__('Cart')) ?>
                </span>

                <?= $heroicons->shoppingCartHtml(
                    "w-8 h-8 md:h-6 md:w-6 hover:text-black",
                    25,
                    25
                ) ?>

                <span x-text="cart.summary_count"
                      class="absolute top-0 right-0 hidden h-5 px-2 py-1 -mt-5 -mr-4 text-xs font-semibold
                        leading-none text-center text-white uppercase transform -translate-x-1
                        translate-y-1/2 rounded-full bg-primary"
                      :class="{
                        'hidden': !cart.summary_count,
                        'block': cart.summary_count }"
                ></span>
            </a>
            <?= $block->getChildHtml('cart.icon.after') ?>

        </div>
    </div>

    <!--Search-->
    <div class="absolute z-10 hidden w-full border-t shadow-sm bg-container-lighter border-container-lighter"
         id="search-content"
         :class="{ 'block': searchOpen, 'hidden': !searchOpen }"
         @click.away="searchOpen = false"
         x-show="true"
    >
        <?= $block->getChildHtml('header-search'); ?>
    </div>

    <!--Cart Drawer-->
    <?= $block->getChildHtml('cart-drawer'); ?>
    <?= $block->getChildHtml('cart.drawer.after'); ?>

    <!--Authentication Pop-Up-->
    <?= $block->getChildHtml('authentication-popup'); ?>
</div>

